### ISSUE TITLE
Invalid yaml files left after bundle removal.

### ISSUE THREAD

**Issue by ianef** [williarin/cook#10]
If I create say a routing yaml file in the config directory of the parent project, it's created and works OK. However when my bundle is removed if doesn't remove all of the file contents and leaves invalid yaml.

Here are the contents of my cook.yaml file. It updates the parent project bundles.php and adds a bundle specific routing file.
```yaml
files:
    '%CONFIG_DIR%/bundles.php':
        type: php_array
        entries:
            Xact\OPCacheDashboard\XactOPCacheDashboardBundle:
                dev: true
                test: true
        filters:
            keys: [class_constant]
            values: [single_line_array]

    '%CONFIG_DIR%/routes/xact_opcache_dashboard.yaml':
        type: yaml
        content: |
            xact_opcache_dashboard:
                resource: "@XactOPCacheDashboardBundle/config/routes.yaml"
```
This creates a ./config/routes/xact_opcache_dashboard.yaml in the parent project as follows:
```yaml
xact_opcache_dashboard:
###> xactsystems/opcache-dashboard ###
    resource: "@XactOPCacheDashboardBundle/config/routes.yaml"
###< xactsystems/opcache-dashboard ###
```

Notice that the surrounding quotes do not include the initial label.

When the bundle is removed, only the contents in my config file that are within the comments section get removed. This leaves an invalid label that has no content and causes errors:
```yaml
xact_opcache_dashboard:
```

This results in:
```txt
The definition of "xact_opcache_dashboard" in ".../config/routes/xact_opcache_dashboard.yaml" must be a YAML array.
```

**Comment by williarin** [comment]
By re-reading the documentation I found that this feature was also implemented using `uninstall_empty_sections: true`:

```
files:
    config/routes.yaml:
        type: yaml
        source: |
            other_routes:
                resource: .
                type: other_routes_loader
        uninstall_empty_sections: true
```
