### ISSUE TITLE
Yaml merger uninstall could be tweaked

### ISSUE THREAD

**Issue by benwick** [williarin/cook#8]
Let us say, we have the following `config/routes.yaml`

```
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
```

And we have this recipe:

```
files:
    config/routes.yaml:
        type: yaml
        source: |
            other_routes:
                resource: .
                type: other_routes_loader
```

After recipe execution the yaml looks like this:

```
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

other_routes:
###> example/other-routes ###
    resource: .
    type: other_routes_loader
###> example/other-routes ###
```

This structure will make some problems when uninstalling the recipe. The top level `other_routes:` will stay - symfony for example does not like this. If a top level entry is created (did not exist before), the comment line should start before this entry. And while uninstalling, the entire added structure should be removed. And if the yaml would be empty after this, it could be removed too (maybe?).
